import React from "react";
import Head from "next/head";
import Dropdown from "@/components/common/Dropdown";
import SearchUser from "@/components/contacts/SearchUser";
import CheckBox from "@/components/contacts/CheckBox";
import PaginationComponent from "@/components/common/PaginationComponent";

export default function contacts() {
  return (
    <>
      <Head>
        <title>Funadiq</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full flex flex-col  p-[40px] overflow-x-hidden">
        <div className="flex-1 self-stretch border-[2px] border-[#838383] border-dashed  rounded-lg relative">
          <div className="flex flex-row justify-between items-center px-[40px] pt-[40px] ">
            <div>
              <h1 className="text-[#626FC1]  text-2xl font-medium">Contacts</h1>
            </div>

            <div className="relative flex flex-row items-center space-x-[12px]">
              <Dropdown />
              <SearchUser />
            </div>
          </div>

          <div
            className=" mx-[40px] py-[20px]  relative my-[20px]"
            style={{
              border: "1.5px dashed #838383",
              "border-radius": "10px",
            }}
          >
            {/* Table start */}
            <table className="table-fixed w-full">
              <thead>
                <tr>
                  <th className="pl-[20px] pb-[20px] border-b  border-dashed border-[#838383] w-[100px] ">
                    <CheckBox />
                  </th>
                  <th className="table_th w-[150px] ">Sr.No</th>
                  <th className="table_th  ">User ID</th>
                  <th className="table_th ">Name</th>
                  <th className="table_th ">Mobile</th>
                  <th className="table_th ">Action</th>
                </tr>
              </thead>
              <tbody>
                {new Array(10).fill(null).map((item, index) => {
                  return (
                    <tr key={index + ""}>
                      <td className="pl-[20px]  py-[20px]  border-t  border-dashed border-[#838383] ">
                        <CheckBox />
                      </td>
                      <td className="table_td">{"0" + index}</td>
                      <td className="table_td">U-ID-12345</td>
                      <td className="table_td">Abdullah Ahsan Khan</td>
                      <td className="table_td">(92) 333 123 4567</td>
                      <td className=" py-[20px]  border-t  border-dashed border-[#838383]">
                        <div className="w-[140px] py-[5px] cursor-pointer rounded-lg text-center text-white font-semibold font-reem-kufi text-base bg-[#40B98B]">
                          <h1>Fetch Contacts</h1>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
            {/* Table end */}
          </div>
          <div className="mx-[40px] mb-[20px]">
            <PaginationComponent />
          </div>
        </div>
      </div>
    </>
  );
}
