import Head from "next/head";

import useSWR from "swr";
import Loader from "../components/common/Loader";



export default function Home() {
  
  const {data,isLoading,mutate} = useSWR("https://funadiq-wali-chat-backend-me3cjxa1p-farooq-funadiqcom-s-team.vercel.app/stats", (apiURL) =>
    fetch(apiURL).then((res) => res.json())
  );


  return (
    <>
      <Head>
        <title>Funadiq</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full flex p-[40px]">
        <div className="flex-1 self-stretch border-[2px] border-[#838383] border-dashed  rounded-lg px-[40px] pt-[40px]">
          <h1 className="text-[#626FC1]  text-2xl font-medium">Dashboard</h1>
          <div className="flex flex-row items-center gap-[20px] mt-[30px] flex-wrap">
            {Array.isArray(data?.data) && data.data.map((item, index) => {
              return <StatsItem data={item} key={index + ""} />;
            })}
          </div>
        </div>
      </div>
      {isLoading && <Loader/>}
    </>
  );
}

const StatsItem = ({ data }) => {
  return (
    <div
      className="min-w-[230px] max-w-[230px] flex-1 h-[130px] rounded-[10px] flex flex-row items-center px-[15px] justify-between shadow-sm"
      style={{
        backgroundColor: data?.color,
      }}
    >
      <div>
        <h1 className="text-white font-reem-kufi font-medium text-sm">No.of</h1>
        <h3 className="text-white font-reem-kufi font-medium text-xl max-w-[100px] ">
          {data?.title}
        </h3>
      </div>
      <div>
        <h1 className="text-white font-reem-kufi font-medium text-5xl">
          {data?.count}
        </h1>
      </div>
    </div>
  );
};
