import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

export default function messages() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Funadiq</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full flex p-[40px]">
        <div className="flex-1 self-stretch border-[2px] border-[#838383] border-dashed  rounded-lg ">
          <h1 className="text-[#626FC1] pl-[40px] pt-[40px] text-2xl font-medium">
            Message
          </h1>
          <div className="px-[40px] mt-[30px]">
            {/* Inputs start here */}
            <div className="flex flex-row space-x-[30px] ">
              <div className="h-[50px] flex-1  border-[2px] border-[rgba(131, 131, 131, 1)] border-dashed rounded-lg relative overflow-hidden">
                <input
                  className=" w-full h-full border-none outline-none px-[20px] font-reem-kufi"
                  placeholder="Message limit (Max 90)"
                />
              </div>
              <div className="h-[50px] flex-1 border-2  border-[rgba(131, 131, 131, 1)] border-dashed rounded-lg relative overflow-hidden">
                <input
                  className=" w-full h-full border-none outline-none px-[20px] font-reem-kufi"
                  placeholder="Message delay time (Min 9 sec)"
                />
              </div>
            </div>
            <div className="h-[270px] flex-1 border-2 mt-[20px]  border-[rgba(131, 131, 131, 1)] border-dashed rounded-lg relative overflow-hidden">
              <textarea
                className=" w-full h-full border-none outline-none px-[20px] pt-[10px] font-reem-kufi"
                placeholder="Write your message here.."
              />
            </div>
            {/* Inputs end here */}
            <div className="mt-[40px] flex items-center justify-between">
              <div>
                <div className="flex flexrow space-x-[10px] ">
                  <div
                    className="cursor-pointer h-[44px] w-[200px] bg-[#40B98B] rounded-lg flex items-center justify-center"
                    onClick={() => router.push("/uploadimage")}
                  >
                    <h1 className="text-lg font-medium text-white font-reem-kufi">
                      Upload Image
                    </h1>
                  </div>
                  <div
                    className="cursor-pointer h-[44px] w-[200px] bg-[#67A6D7] rounded-lg flex items-center justify-center"
                    onClick={() => router.push("/uploadfile")}
                  >
                    <h1 className="text-lg font-medium text-white font-reem-kufi">
                      Import a CSV
                    </h1>
                  </div>
                </div>
                <div
                  className="cursor-pointer h-[44px] mt-4 bg-[#626FC1] rounded-lg flex items-center justify-center"
                  onClick={() => router.push("/contacts")}
                >
                  <h1 className="text-lg font-medium text-white font-reem-kufi">
                    Import Contacts
                  </h1>
                </div>
              </div>
              <div className="cursor-pointer h-[44px] mt-4 w-[200px] bg-[#67A6D7] rounded-lg flex items-center justify-center">
                <h1 className="text-lg font-medium text-white font-reem-kufi">
                  Send
                </h1>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
