import Head from "next/head";
import React from "react";

export default function settings() {
  return (
    <>
      <Head>
        <title>Funadiq</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full flex p-[40px]">
        <div className="flex-1 self-stretch border-[2px] border-[#838383] border-dashed  rounded-lg flex flex-col ">
          <h1 className="text-[#626FC1] pl-[40px] pt-[40px] text-2xl font-medium">
            Settings
          </h1>
          <div className="pl-[40px] pt-[40px]">
            <h1 className="font-reem-kufi font-medium text-base text-[#838383]">API Key</h1>
            <input
              className="h-[45px] px-2 rounded-xl w-[400px] outline-none mt-2"
              placeholder="Enter API Key."
              style={{
                'border': "1.5px dashed #838383",
                "border-radius": "10px",
              }}
            />
          </div>
        </div>
      </div>
    </>
  );
}
